### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by VasilevIvanVladimirovich** [PBernalPolo/test_MKF#2]
Hi, I was analyzing your java code and the original C++ code and noticed a discrepancy in this line:
https://github.com/PBernalPolo/test_MKF/blob/29c46e17ddc709b18a2365e2c1746f7e78be5c51/test_MKF/MEKFcO.java#LL62C29-L62C29

`G[i+j*3] += delta[i+1]*delta[j+1]/delta[0];`

C++ line: https://github.com/PBernalPolo/OrientationEstimationTest2017/blob/a1f3f2dc06617a2a16a26c64a205ad132cab8a8f/cpp/MEKFcO.cpp#LL89C6-L89C6

` G[i+j*3]-= delta[i+1]*delta[j+1]/delta[0];`

Why do you have a different sign?

**Comment by pbernalpolo** [comment]
Hi @VasilevIvanVladimirovich . You found a bug! The right version is the Java one. This can be checked looking at Table 4 in https://www.mdpi.com/1424-8220/19/1/149# .  I proceed to correct the c++ version. Thank you for your help!
